name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_blue_plus: ^1.32.12
  get: ^4.6.5
  syncfusion_flutter_core: ^28.1.33
  syncfusion_flutter_charts: ^28.1.33
  shared_preferences: ^2.3.5
  collection: ^1.19.0
  intl: ^0.20.1
  geolocator: ^13.0.2
  vibration: ^3.1.3
  flutter_tts: ^4.2.2
  pdf: ^3.11.3
  path_provider: ^2.1.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/